############################################################
# Dockerfile to build Flask App
# Based on
############################################################

# Set the base image
FROM ubuntu:latest


RUN apt-get update && apt-get install -y apache2 \ 
    libapache2-mod-wsgi \
    python \
    python-dev\
    python-pip \
    
 && apt-get clean \
 && apt-get autoremove \
 && rm -rf /var/lib/apt/lists/*

RUN apt-get install mysql-server

RUN a2enmod wsgi

# Copy over and install the requirements
COPY ./FlaskApp/requirements.txt /var/www/FlaskApp/FlaskApp/requirements.txt
RUN pip install -r /var/www/FlaskApp/FlaskApp/requirements.txt

# Copy over the apache configuration file and enable the site
COPY ./FlaskApp.conf /etc/apache2/sites-available/FlaskApp.conf
RUN a2ensite FlaskApp


# Copy over the wsgi file
COPY ./flaskapp.wsgi /var/www/FlaskAPP/flask.wsgi

COPY ./FlaskApp /var/www/FlaskApp/


RUN service apache2 restart
RUN service mysql start


EXPOSE 80

WORKDIR /var/www/FlaskApp

CMD apachectl start 
  

